trigger:
  branches:
    include:
      - main

  paths:
    include:
      - "rumpole-ui"

pool:
  vmImage: ubuntu-latest

variables:
  REACT_APP_BUILD_NUMBER: $(Build.BuildNumber)

steps:
  - task: Npm@1
    inputs:
      command: "custom"
      workingDir: "rumpole-ui"
      customCommand: "ci --omit=dev --ignore-scripts"
    displayName: "npm install"

  - task: Npm@1
    inputs:
      command: "custom"
      workingDir: "rumpole-ui"
      customCommand: "run prettier:check"
    displayName: "npm prettier:check"

  - task: Npm@1
    inputs:
      command: "custom"
      workingDir: "rumpole-ui"
      customCommand: "run build"
    displayName: "npm build"

  - task: Npm@1
    inputs:
      command: "custom"
      workingDir: "rumpole-ui"
      customCommand: "run test:ci"
    displayName: "npm test"

  - task: Npm@1
    inputs:
      command: "custom"
      workingDir: "rumpole-ui"
      customCommand: "run cy:ci"
    displayName: "cypress run tests"

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: "rumpole-ui/build"
      ArtifactName: "rumpole-ui-drop"
      publishLocation: "Container"

  - task: PublishTestResults@2
    inputs:
      testResultsFormat: "JUnit"
      testResultsFiles: "rumpole-ui/report/test-*.xml"
      mergeTestResults: true

  - task: Npm@1
    inputs:
      command: "custom"
      workingDir: "rumpole-ui"
      customCommand: "run cy:report"
    displayName: "generate cypress html report"

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: "rumpole-ui/report"
      ArtifactName: "rumpole-ui-report"
      publishLocation: "Container"
