#!/usr/bin/env node

const items = [
  { id: "16", name: "British Cattle Movement Service" },
  { id: "17", name: "Food Standards Agency" },
  { id: "18", name: "NATIS" },
  { id: "19", name: "MOD" },
  { id: "20", name: "NCA" },
  { id: "21", name: "Local Authority" },
  {
    id: "22",
    name: "Independent Office for Police Conduct (IOPC)",
    children: [],
  },
  { id: "23", name: "Health and Safety Executive (HSE)" },
  { id: "24", name: "Home Office Immigration" },
  { id: "25", name: "HMRC" },
  { id: "26", name: "ROCU" },
  { id: "27", name: "SO15" },
  { id: "28", name: "Police Scotland" },
  { id: "29", name: "Counter Terrorism Police" },
  { id: "30", name: "Avon and Somerset Constabulary" },
  { id: "31", name: "Bedfordshire Police" },
  { id: "32", name: "Cambridgeshire Constabulary" },
  { id: "33", name: "Cheshire Constabulary" },
  { id: "34", name: "City of London Police" },
  { id: "35", name: "Cleveland Police" },
  { id: "36", name: "Cumbria Constabulary" },
  { id: "37", name: "Derbyshire Constabulary" },
  { id: "38", name: "Devon & Cornwall Police" },
  { id: "39", name: "Dorset Police" },
  { id: "40", name: "Durham Constabulary" },
  { id: "41", name: "Essex Police" },
  { id: "42", name: "Gloucestershire Constabulary" },
  { id: "43", name: "Greater Manchester Police" },
  { id: "44", name: "Hampshire Constabulary" },
  { id: "45", name: "Hertfordshire Constabulary" },
  { id: "46", name: "Humberside Police" },
  { id: "47", name: "Kent Police" },
  { id: "48", name: "Lancashire Constabulary" },
  { id: "49", name: "Leicestershire Police" },
  { id: "50", name: "Lincolnshire Police" },
  { id: "51", name: "Merseyside Police" },
  { id: "52", name: "Metropolitan Police Service" },
  { id: "53", name: "Norfolk Constabulary" },
  { id: "54", name: "North Yorkshire Police" },
  { id: "55", name: "Northamptonshire Police" },
  { id: "56", name: "Northumbria Police" },
  { id: "57", name: "Nottinghamshire Police" },
  { id: "58", name: "South Yorkshire Police" },
  { id: "59", name: "Staffordshire Police" },
  { id: "60", name: "Suffolk Constabulary" },
  { id: "61", name: "Surrey Police" },
  { id: "62", name: "Sussex Police" },
  { id: "63", name: "Thames Valley Police" },
  { id: "64", name: "Warwickshire Police" },
  { id: "65", name: "West Mercia Police" },
  { id: "66", name: "West Midlands Police" },
  { id: "67", name: "West Yorkshire Police" },
  { id: "68", name: "Wiltshire Police" },
  { id: "69", name: "Dyfed-Powys Police" },
  { id: "70", name: "Gwent Police" },
  { id: "71", name: "North Wales Police" },
  { id: "72", name: "South Wales Police" },
  { id: "73", name: "British Transport Police" },
  { id: "74", name: "Civil Nuclear Constabulary" },
  { id: "75", name: "Ministry of Defence Police" },
  { id: "76", name: "National Police Air Service" },
  { id: "77", name: "SEROCU" },
  { id: "78", name: "ERSOU" },
];

items.forEach((item) =>
  console.log(item.name.replace(/ /g, "") + ": " + JSON.stringify(item) + ",")
);
