on:
  push:
    branches:
      - main
      - release/*
      - bug/*
    paths:
      - rumpole-gateway/*
      - RumpoleGateway/*
env:
  functionName: rumpole-gateway
  appName: fa-rumpole-gateway
  buildConfiguration: Release
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use .NET Core sdk
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
      - name: Build
        run: dotnet build ${{ env.functionName }}/${{ env.functionName }}.csproj --configuration ${{ env.buildConfiguration }}
      - name: Run tests
        run: dotnet test ${{ env.functionName }}*tests/${{ env.functionName }}*tests.csproj --configuration ${{ env.buildConfiguration }} /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura
      - name: Copy Coverage To Predictable Location
        run: cp **/*coverage.cobertura.xml coverage/coverage.cobertura.xml
      - name: Code Coverage Summary Report
        uses: irongut/CodeCoverageSummary@v1.0.2
        with:
          filename: coverage/coverage.cobertura.xml
          badge: true
          format: 'markdown'
          output: 'both'
      - name: Add Coverage PR Comment
        uses: marocchino/sticky-pull-request-comment@v2
        if: github.event_name == 'pull_request'
        with:
          recreate: true
          path: code-coverage-results.md
      - name: Publish
        run: dotnet publish ${{ env.functionName }}/${{ env.functionName }}.csproj --configuration ${{ env.BuildConfiguration }} --output ${{ github.workspace }}
      - uses: actions/upload-artifact@v2
        with:
          path: ${{ github.workspace }}
          name: rumpole-gateway-drop