#Error (line 18): the step 'DeleteFiles@1' does not have a conversion path yet
#Error (line 68): the step 'PublishTestResults@2' does not have a conversion path yet
#Error (line 70): the step 'PublishTestResults@2' does not have a conversion path yet
#Error (line 85): the step 'PublishCodeCoverageResults@1' does not have a conversion path yet
on:
  push:
    branches:
      - main
    paths:
      - rumpole-ui
env:
  REACT_APP_BUILD_NUMBER: ${{ github.run_number }}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - # "Error: the step 'DeleteFiles@1' does not have a conversion path yet"
        name: Remove .env file
        run: |
          echo "Error: the step 'DeleteFiles@1' does not have a conversion path yet"
          #task: DeleteFiles@1
          #displayName: Remove .env file
          #inputs:
          #  contents: 
          #    rumpole-ui/.env
      - name: npm install
        run: npm install rumpole-ui
      - name: npm prettier
        run: npm run prettier rumpole-ui
      - name: npm test
        run: npm run test:ci rumpole-ui
      - name: cypress run tests
        run: npm run cy:ci rumpole-ui
      - name: npm build
        run: npm run build rumpole-ui
      - uses: actions/upload-artifact@v2
        with:
          path: rumpole-ui/build
          name: rumpole-ui-drop
      - name: combine unit and cypress coverage
        run: npm run coverage rumpole-ui
      - uses: actions/upload-artifact@v2
        with:
          path: rumpole-ui/cypress/videos
          name: Cypress failure vidoes
        if: always()
      - uses: actions/upload-artifact@v2
        with:
          path: rumpole-ui/report
          name: Unit test report
      - uses: actions/upload-artifact@v2
        with:
          path: rumpole-ui/report-cypress
          name: Cypress test report
      - uses: actions/upload-artifact@v2
        with:
          path: rumpole-ui/coverage
          name: Unit test coverage report
      - uses: actions/upload-artifact@v2
        with:
          path: rumpole-ui/coverage-cypress
          name: Cypress coverage report
      - uses: actions/upload-artifact@v2
        with:
          path: rumpole-ui/coverage-merged
          name: Merged coverage report
      - # "Error: the step 'PublishTestResults@2' does not have a conversion path yet"
        run: |
          echo "Error: the step 'PublishTestResults@2' does not have a conversion path yet"
          #task: PublishTestResults@2
          #inputs:
          #  testresultsformat: JUnit
          #  testresultsfiles: rumpole-ui/report/*.xml
          #  testruntitle: Unit tests
      - # "Error: the step 'PublishTestResults@2' does not have a conversion path yet"
        run: |
          echo "Error: the step 'PublishTestResults@2' does not have a conversion path yet"
          #task: PublishTestResults@2
          #inputs:
          #  testresultsformat: JUnit
          #  testresultsfiles: rumpole-ui/report-cypress/test-*.xml
          #  testruntitle: Cypress tests
          #  mergetestresults: true
      - # "Error: the step 'PublishCodeCoverageResults@1' does not have a conversion path yet"
        run: |
          echo "Error: the step 'PublishCodeCoverageResults@1' does not have a conversion path yet"
          #task: PublishCodeCoverageResults@1
          #inputs:
          #  codecoveragetool: Cobertura
          #  summaryfilelocation: ${{ github.workspace }}/rumpole-ui/coverage-merged/cobertura-coverage.xml