name: Rumpole Gateway
on:
  push:
    branches: main
    paths:
      - rumpole-gateway/*
      - RumpoleGateway/*
  pull_request:
    branches: main
    paths:
      - rumpole-gateway/*
      - RumpoleGateway/*  
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use .NET Core sdk
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build rumpole-gateway/rumpole-gateway.csproj --configuration Release --no-restore
      - name: Run tests
        run: dotnet test rumpole-gateway.tests/rumpole-gateway.tests.csproj --configuration Release /p:CollectCoverage=true /p:CoverletOutput=TestResults/ /p:CoverletOutputFormat=lcov
      - name: Publish coverage report to coveralls.io
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: rumpole-gateway.tests/TestResults/coverage.info
      - name: Publish
        run: dotnet publish rumpole-gateway/rumpole-gateway.csproj --configuration Release --output ${{ github.workspace }}
      - uses: actions/upload-artifact@v2
        with:
          path: ${{ github.workspace }}
          name: rumpole-gateway-drop
