name: Rumpole UI
on:
  push:
    branches: [main]
    paths:
      - rumpole-ui/*
  pull_request:
    branches: [main]
    paths:
      - rumpole-ui/*
  workflow_dispatch:
env:
  REACT_APP_BUILD_NUMBER: ${{ github.run_number }}
defaults:
  run:
    working-directory: rumpole-ui
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: bahmutov/npm-install@v1
        with:
          working-directory: rumpole-ui
      - name: Remove .env file
        run: |
          rm -f \
            rumpole-ui/.env \
      - name: npm prettier
        run: npm run prettier rumpole-ui
      - name: npm test
        run: npm run test:ci rumpole-ui
      - name: cypress run tests
        run: npm run cy:ci rumpole-ui
      - name: npm build
        run: npm run build rumpole-ui
      - uses: actions/upload-artifact@v2
        with:
          path: rumpole-ui/build
          name: rumpole-ui-drop
      - name: combine unit and cypress coverage
        run: npm run coverage rumpole-ui
      - uses: actions/upload-artifact@v2
        with:
          path: rumpole-ui/cypress/videos
          name: Cypress failure vidoes
        if: always()
      - uses: actions/upload-artifact@v2
        with:
          path: rumpole-ui/report
          name: Unit test report
      - uses: actions/upload-artifact@v2
        with:
          path: rumpole-ui/report-cypress
          name: Cypress test report
      - uses: actions/upload-artifact@v2
        with:
          path: rumpole-ui/coverage
          name: Unit test coverage report
      - uses: actions/upload-artifact@v2
        with:
          path: rumpole-ui/coverage-cypress
          name: Cypress coverage report
      - uses: actions/upload-artifact@v2
        with:
          path: rumpole-ui/coverage-merged
          name: Merged coverage report
      - name: Unit tests
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          junit_files: "rumpole-ui/report/*.xml"
      - name: Cypress tests
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          junit_files: "rumpole-ui/report-cypress/test-*.xml"
      - name: Code coverage results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          xunit_files: "${{ github.workspace }}/rumpole-ui/coverage-merged/cobertura-coverage.xml"
