name: Rumpole Gateway
on:
  push:
    branches:
      - main
      - release/*
      - bug/*
      - feature/*
    paths:
      - rumpole-gateway/*
      - RumpoleGateway/*  
  pull_request:
    branches:
      - main
      - release/*
      - bug/*
      - feature/*
    paths:
      - rumpole-gateway/*
      - RumpoleGateway/*
env:
  functionName: rumpole-gateway
  appName: fa-rumpole-gateway
  buildConfiguration: Release
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use .NET Core sdk
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build ${{ env.functionName }}/${{ env.functionName }}.csproj --configuration ${{ env.buildConfiguration }} --no-restore
      - name: Run tests
        run: dotnet test ${{ env.functionName }}*tests/${{ env.functionName }}*tests.csproj --configuration ${{ env.buildConfiguration }} /p:CollectCoverage=true /p:CoverletOutput=TestResults/ /p:CoverletOutputFormat=lcov
      - name: Publish coverage report to coveralls.io
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: ${{ env.functionName }}/${{ env.functionName }}*tests/TestResults/coverage.info
      - name: Publish
        run: dotnet publish ${{ env.functionName }}/${{ env.functionName }}.csproj --configuration ${{ env.BuildConfiguration }} --output ${{ github.workspace }}
      - uses: actions/upload-artifact@v2
        with:
          path: ${{ github.workspace }}
          name: rumpole-gateway-drop