name: Rumpole Gateway
on:
  push:
    branches:
      - main
      - release/*
      - bug/*
      - feature/*
    paths:
      - rumpole-gateway/*
      - RumpoleGateway/*  
  pull_request:
    branches:
      - bug/*
      - feature/*
    paths:
      - rumpole-gateway/*
      - RumpoleGateway/*
env:
  functionName: rumpole-gateway
  appName: fa-rumpole-gateway
  buildConfiguration: Release
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use .NET Core sdk
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build ${{ env.functionName }}/${{ env.functionName }}.csproj --configuration ${{ env.buildConfiguration }} --no-restore
      - name: Run tests
        run: dotnet test ${{ env.functionName }}*tests/${{ env.functionName }}*tests.csproj --configuration ${{ env.buildConfiguration }} --no-build --verbosity normal --collect:"XPlat Code Coverage" --logger trx --results-directory coverage
      - name: Copy Coverage To Predictable Location
        run: cp coverage/*/coverage.cobertura.xml coverage/coverage.cobertura.xml
      - name: Code Coverage Report
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: coverage/**/coverage.cobertura.xml
          badge: true
          fail_below_min: true
          format: markdown
          hide_branch_rate: false
          hide_complexity: true
          indicators: true
          output: both
          thresholds: '60 80'
      - name: Add Coverage PR Comment
        uses: marocchino/sticky-pull-request-comment@v2
        if: github.event_name == 'pull_request'
        with:
          recreate: true
          path: code-coverage-results.md
      - name: Adding markdown to build summary
        run: cat code-coverage-results.md >> $GITHUB_STEP_SUMMARY
      - name: Publish
        run: dotnet publish ${{ env.functionName }}/${{ env.functionName }}.csproj --configuration ${{ env.BuildConfiguration }} --output ${{ github.workspace }}
      - uses: actions/upload-artifact@v2
        with:
          path: ${{ github.workspace }}
          name: rumpole-gateway-drop