name: "Security Scanning"
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  workflow_dispatch:
permissions: write-all
jobs:
  scan:
    name: Security Scan
    uses: CPS-Innovation/.github/.github/workflows/security-scan.yml@main
    secrets: inherit
